kind: Deployment
apiVersion: apps/v1
metadata:
   name: my-project  
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: my-project  
   template:
      metadata:
        labels:
          app: my-project  
      spec:
       containers:
        - name: my-project  
          image: karimabdelbasit/pipeline-myproject
          imagePullPolicy: Always
          ports:
          - containerPort: 80
