kind: Service                             
apiVersion: v1
metadata:
  name: my-project
  labels:
    app: my-project
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: my-project                    
  type: LoadBalancer                   
